"""AI-driven scan planning"""

from typing import Dict, Any, List, Optional
from dataclasses import dataclass
import os
from openai import OpenAI


@dataclass
class ScanPlan:
    """Scan plan generated by AI"""
    target: str
    scan_type: str
    recommended_tools: List[str]
    scan_phases: List[Dict[str, Any]]
    estimated_duration_seconds: int
    warnings: List[str]
    risk_level: str  # low, medium, high, critical


class ScanPlanner:
    """AI-powered scan planning"""

    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key or os.getenv("OPENROUTER_API_KEY") or os.getenv("ANTHROPIC_API_KEY")
        if not self.api_key:
            raise ValueError("OPENROUTER_API_KEY required")
        
        self.client = OpenAI(
            base_url="https://openrouter.ai/api/v1",
            api_key=self.api_key
        )
        self.model = os.getenv("AI_MODEL", "google/gemini-2.0-flash-exp:free")

    async def create_scan_plan(
        self,
        target: str,
        scan_type: str,
        context: Optional[Dict[str, Any]] = None
    ) -> ScanPlan:
        """
        Use AI to create an optimal scan plan.
        
        Args:
            target: Target to scan (IP, domain, network, etc.)
            scan_type: Type of scan (wifi, network, web, cloud)
            context: Additional context about the target
            
        Returns:
            ScanPlan with recommendations
        """
        
        prompt = self._build_scan_planning_prompt(target, scan_type, context or {})
        
        # Use AI to analyze and plan
        message = self.client.chat.completions.create(
            model=self.model,
            max_tokens=2000,
            messages=[{
                "role": "user",
                "content": prompt
            }]
        )
        
        # Parse AI response
        plan = self._parse_scan_plan_response(message.choices[0].message.content, target, scan_type)
        
        return plan

    def _build_scan_planning_prompt(
        self,
        target: str,
        scan_type: str,
        context: Dict[str, Any]
    ) -> str:
        """Build prompt for scan planning"""
        
        return f"""You are a cybersecurity expert planning a {scan_type} security scan.

Target: {target}
Scan Type: {scan_type}
Additional Context: {context}

Please create a comprehensive scan plan that includes:

1. Recommended Tools: List of specific tools to use
2. Scan Phases: Step-by-step phases of the scan with timing
3. Estimated Duration: Total time in seconds
4. Warnings: Any potential issues or risks
5. Risk Level: Assessment of target risk (low/medium/high/critical)

For each phase, specify:
- Phase name
- Tools to use
- Duration in seconds
- What to look for

Respond in a structured format that can be parsed.

Example format:
TOOLS: nmap, nikto, sqlmap
PHASES:
1. Reconnaissance (300s) - nmap port scan
2. Vulnerability scanning (600s) - nikto web scan
3. Deep testing (900s) - sqlmap injection testing
DURATION: 1800
WARNINGS: May trigger IDS/IPS, ensure authorization
RISK: medium
"""

    def _parse_scan_plan_response(
        self,
        response: str,
        target: str,
        scan_type: str
    ) -> ScanPlan:
        """Parse AI response into ScanPlan"""
        
        # Default values
        tools = []
        phases = []
        duration = 600  # 10 minutes default
        warnings = []
        risk_level = "medium"
        
        # Parse response (simplified)
        lines = response.split('\n')
        current_section = None
        
        for line in lines:
            line = line.strip()
            
            if line.startswith("TOOLS:"):
                tools_str = line.replace("TOOLS:", "").strip()
                tools = [t.strip() for t in tools_str.split(',')]
            
            elif line.startswith("PHASES:"):
                current_section = "phases"
            
            elif line.startswith("DURATION:"):
                try:
                    duration = int(line.replace("DURATION:", "").strip())
                except:
                    pass
            
            elif line.startswith("WARNINGS:"):
                warnings_str = line.replace("WARNINGS:", "").strip()
                warnings = [w.strip() for w in warnings_str.split(',')]
            
            elif line.startswith("RISK:"):
                risk_level = line.replace("RISK:", "").strip().lower()
            
            elif current_section == "phases" and line and line[0].isdigit():
                # Parse phase line
                parts = line.split('-', 1)
                if len(parts) == 2:
                    phase_info = parts[0].strip()
                    phase_desc = parts[1].strip()
                    
                    # Extract duration if present
                    phase_duration = 300  # default 5 min
                    if '(' in phase_info and 's)' in phase_info:
                        try:
                            dur_str = phase_info[phase_info.find('(')+1:phase_info.find('s)')]
                            phase_duration = int(dur_str)
                        except:
                            pass
                    
                    phases.append({
                        "description": phase_desc,
                        "duration": phase_duration,
                        "tools": tools  # Simplified - use all tools
                    })
        
        return ScanPlan(
            target=target,
            scan_type=scan_type,
            recommended_tools=tools,
            scan_phases=phases,
            estimated_duration_seconds=duration,
            warnings=warnings,
            risk_level=risk_level
        )

    async def adjust_plan_for_findings(
        self,
        original_plan: ScanPlan,
        findings: List[Dict[str, Any]]
    ) -> ScanPlan:
        """Adjust scan plan based on preliminary findings"""
        
        prompt = f"""Based on these preliminary findings, should we adjust the scan plan?

Original Plan: {original_plan.scan_type} scan of {original_plan.target}
Findings so far: {findings}

Should we:
1. Add more deep scans?
2. Skip unnecessary phases?
3. Change tools?
4. Extend duration?

Provide recommendations."""

        # Use AI to analyze
        message = self.client.chat.completions.create(
            model=self.model,
            max_tokens=1000,
            messages=[{"role": "user", "content": prompt}]
        )
        
        # For now, return original plan
        # TODO: Parse AI suggestions and modify plan
        return original_plan
